@extends('admin.layouts.public')

@section('page-title', 'End User License Agreement')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="page-header">
                    <h1 class="page-title">
                        End User License Agreement
                    </h1>
                </div>

                <div class="card card-lg">
                    <div class="card-body">
                        <p>
                            This End User License Agreement (“<b>EULA</b>”) is a legal agreement between:
                        </p>
                        <ol>
                            <li>You (both the individual installing the Software and any other person or entity on behalf of which such individual is acting) (“<b>you</b>” or “<b>End User</b>”); and</li>
                            <li>The Employer Branding Monitor (“<b>The Employer Branding Monitor</b>”), a solution of aTalent Shanghai, Registration Number 91310000MA1G0BK437, located at Shanghai Office (Headquarters), Soho Xintiandi, Tower A, Unit 250, 388 Madang Road, Shanghai, 200025, People's Republic of China; governing your acquisition and use of The Employer Branding Monitor’s proprietary Software (as defined hereinafter), either directly from The Employer Branding Monitor or indirectly through a Reseller.</li>
                        </ol>

                        <h3 class="mb-3 mt-5">1. Definitions</h3>
                        <ul>
                            <li>1.1 “Concurrent User” means any individual user of the Software who is authorized by an End User to access or use the Software, it being understood that each simultaneous login to the Software (through active browser sessions) shall be deemed to constitute one Concurrent User. Hence, when one user is simultaneously logged in to the Software from two different devices, this constitutes two Concurrent User sessions;</li>
                            <li>1.2 “Confidential Information” means the Software, its source code, the content of the Documentation, any financial, statistical, business, technical, copyright, and confidential or proprietary information relating to the Software or to The Employer Branding Monitor’s business, software, products and/or services, which is disclosed by Reseller, The Employer Branding Monitor or its affiliates to End User, or which is deduced from the Software or The Employer Branding Monitor’s business, software, products and/or services by End User;</li>
                            <li>1.3 “Delivery Date” means the date on which the relevant License keys are being activated by or in the name and on behalf of the End User;</li>
                            <li>1.4 “Documentation” means all of The Employer Branding Monitor’s user manuals, operating instructions and other documents relating to the Software, as generally made available from time to time to End Users;</li>
                            <li>1.5 “End User” means the final purchaser or licensee acquiring a License either (1) for a certain number of its own internal Concurrent Users or Named Users; or (2) for certain third-party Concurrent Users or Named Users acquiring remote access to the Software as part of End User’s hosting deployment.</li>
                            <li>1.6 “Fees” means the Subscription License Fees, Perpetual License Fees, Maintenance and Support Fees or Other Fees as defined in this EULA.</li>
                            <li>1.7 “Initial License Term” means, with respect to a Subscription License, the initial minimum fixed license term as set out in the Order Form during which the Software is licensed to End User, as further described in Section 12.1;</li>
                            <li>1.8 “Initial Maintenance Period” means, with respect to a Perpetual License, the mandatory Maintenance Period of one year or three years, as further defined in the Order Form, beginning on the Delivery Date</li>
                            <li>1.9 “License” means either the Perpetual or the Subscription License granted by The Employer Branding Monitor to End User in view of using and accessing the Software and the Documentation, as further described in Section 3;</li>
                            <li>1.10 “License Fees” means the fees due by End User for the License, which are payable to the Reseller (or, when purchased directly from The Employer Branding Monitor, to The Employer Branding Monitor);</li>
                            <li>1.11 “License Term” means, (i) in respect of a Subscription License, the Initial License Term and the Subsequent License Term(s) (if any); and (ii) in respect of a Perpetual License, the indefinite term commencing on the Delivery Date;</li>
                            <li>1.12 “Maintenance Period” means (i) in respect of a Subscription License, the term corresponding to the License Term; and (ii) in respect of a Perpetual License, the Initial Maintenance Period and the Subsequent Maintenance Period(s) (if any), during which End User is entitled to receive Maintenance and Support Services from Reseller (or from The Employer Branding Monitor when the corresponding License was purchased directly from The Employer Branding Monitor) pursuant to Section 8;</li>
                            <li>1.13 “Maintenance and Support Services” means maintenance and technical support services for the Software provided by Reseller (or by The Employer Branding Monitor when the corresponding License was purchased directly from The Employer Branding Monitor), including periodic distribution of bug fixes and Updates (excluding however, for the avoidance of doubt, Upgrades), all as scheduled by The Employer Branding Monitor;</li>
                            <li>1.14 “Maintenance and Support Fees” means the fees due by End User in respect of Maintenance and Support Services pursuant to this EULA, which are payable to Reseller (or The Employer Branding Monitor, as the case may be);</li>
                            <li>1.15 “Named User” means either:</li>
                            <li>1.15.1 a ‘Person-based Named User’, i.e. any unique licensed user of the Product who is authorized by the End User to access or use the Software – regardless of whether the individual is actively accessing the Software, and regardless of the number of simultaneous logins from such individual to the Software at any given time; or</li>
                            <li>1.15.2 a ‘Device-based Named User’, i.e. any individual user of the Product who is authorized by the End User to access or use the Software from a certain device, it being understood that each device from which the individual user is authorized to login to the Software shall be deemed to constitute one Named User.</li>
                            <li>All Named Users must be registered in the database of Named Users that is kept by The Employer Branding Monitor (the “The Employer Branding Monitor Database”), it being understood that in case of Device-based Named Users, this registration shall refer to the number of relevant devices only.</li>
                            <li>1.16 “Professional Services” means those additional services provided by The Employer Branding Monitor to End User in the framework of the installation and/or maintenance of the Software (other than the Maintenance and Support Services), which may be invoiced separately to End User. Professional Services shall (amongst others) include so-called “first time installs” consisting of preparation of the End User’s environment by advising configurations of the firewall GPO’s and other application-related settings; and implementing the The Employer Branding Monitor configurations in respect of such new installations.</li>
                            <li>1.17 “Misuse” means (i) any use of the Software otherwise than in accordance with this EULA or any other written and explicit instructions provided by The Employer Branding Monitor, (ii) (attempted) modification or change of the Software not performed by or on behalf of The Employer Branding Monitor; (iii) merging the Software with any software or hardware which is not supplied by or on behalf of The Employer Branding Monitor or which is not authorized by The Employer Branding Monitor to be so merged by End User; and (iv) negligence, improper installation or operation, accident, or other conditions other than normal use which might cause the Software to fail; For avoidance of doubt, installing any other software on, or making modification to the The Employer Branding Monitor virtual appliance is not allowed for Pen testing, backup, monitoring, or other purposes.</li>
                            <li>1.18 “Order Form” means The Employer Branding Monitor’s or Reseller’s order form, scope of work or other written communication between you and The Employer Branding Monitor pursuant to which you place an order for one or more Licenses concurrently or prior to the effectiveness of this EULA;</li>
                            <li>1.19 “Perpetual License” shall have the meaning as set out in Section 3.2;</li>
                            <li>1.20 “Reseller” means the individual or company acquiring Licenses from The Employer Branding Monitor in view of transferring such Licenses to the End Users, either directly or indirectly, through other business intermediaries.</li>
                            <li>1.21 “Software” means the innovative workspace aggregator software solution developed by The Employer Branding Monitor, which enables the mobile enterprise, consisting of a broker platform that gives users secure access to corporate IT resources such as company applications and data, and which is licensed by The Employer Branding Monitor to End User under this EULA, including Updates (but excluding Upgrades).  Although some of the Software components may work together with, rely on, or be relicensed as open source software components by The Employer Branding Monitor, such open source software components are subject to their respective separate licenses as specified in the Documentation and shall not be deemed as part of the Software and thus not subject to this EULA, provided that by entering into this EULA, the End User agrees to be bound by such separate licenses (if any) as are identified in the Documentation;</li>
                            <li>1.22 “Subscription License” shall have the meaning as set out in Section 3.1;</li>
                            <li>1.23 “Subsequent License Term” means, with respect to a Subscription License, any subsequent term of even duration as the Initial License Term which follows such Initial License Term, during which The Employer Branding Monitor licenses the Software to End User, as further described in Section 12.1;</li>
                            <li>1.24 “Subsequent Maintenance Period” means, with respect to a Perpetual License, any subsequent terms of one (1) or three (3) years each, as the case may be, following the Initial Maintenance Period, during which End User shall be entitled to receive Maintenance and Support Services from Reseller or The Employer Branding Monitor, as the case may be, as further described in Section 8;</li>
                            <li>1.25 “Update” means a minor amendment of the Software, which may include minor functionality enhancements, bug fixes or performance or error corrections and shall be marked as a new sub-version number (“1.X”), sub-sub-version number (“1.X.X”) or sub-sub-sub-version number (“1.X.X.X”). For example, should End User purchase the Software under version 1.1.1 an Update shall commence under version number 1.2.0. The assignment to the category of Update or Upgrade (as defined hereinafter) shall be at the sole discretion of The Employer Branding Monitor;</li>
                            <li>1.26 “Upgrade” means a material amendment of the Software which contains new features and/or major performance improvements, such as new modules, etc., and shall be marked as a new version number. For example, should End User purchase the Software under version 1.X.X, an Upgrade shall commence under number 2.0.0. An Upgrade may be licensed and/or priced separately from the previous version of the Software or made available for an additional fee, as determined by The Employer Branding Monitor at its sole discretion.</li>
                            <li>1.27 “Version” means each Software version identified by a number of three or four digits separated by a dot (for instance 1.2.3. or 1.2.3.4.), whereby the first digit indicates the major release (Upgrade), the second digit indicates a minor release (Update), the third digit indicates the maintenance release (minor Update), and the fourth digit, if any, might refer to the builder number (minor Update). Parties acknowledge and agree that each Upgrade (i.e. each increase of the first digit) and/or each Update (i.e.) each increase of the second digit) shall each constitute a new Version of the Product.</li>
                            <li>1.28 “Warranty Period” has the meaning in Section 9.1 of this EULA;</li>
                            <li>1.29 “Workaround” means a suggested set of actions or recommendations intended, when properly implemented, to materially restore the functionality of the Software or to provide equivalent or similar functionality.</li>
                            <li>1.30 “Internal Use – Not For Resale Licenses” means any License which is granted by The Employer Branding Monitor to Reseller in view of Reseller’s own internal use of the Software as an End User, which may not be sold, distributed or otherwise transferred by Reseller.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">2. Acceptance and modifications</h3>
                        <ul>
                            <li>2.1 Acceptance. By clicking “accept” or installing and/or using the Software, you are confirming your acceptance of the Software and agreeing to become bound by the terms of this EULA and acknowledge that it is enforceable as a written contract signed by you.
                                <ul>
                                    <li>If you are under the age of 18, you are not permitted to use the Software or provide your personal information to us without the consent of your parent or guardian who must first accept this Agreement and administer the Software on your behalf.</li>
                                    <li>If you are entering into this EULA on behalf of a company or other legal entity, you represent that you have the authority to bind such entity and its affiliates to these terms and conditions.</li>
                                </ul>

                                IF YOU DO NOT AGREE WITH THE TERMS AND CONDITIONS OF THIS EULA, OR IF YOU DO NOT HAVE THE LEGAL AGE OR AUTHORITY TO ENTER INTO THIS AGREEMENT, DO NOT INSTALL OR USE THE SOFTWARE, AND YOU MUST NOT ACCEPT THIS EULA.

                                This EULA shall apply only to the Software supplied by The Employer Branding Monitor regardless of whether other software is referred to or described herein. The terms also apply to any Updates, supplements, Internet-based services, and support services for the Software.

                                If you register for a “Proof of Concept”, demo or trial version of the Software, either for free or against payment of a certain price (hereinafter referred to as a “POC Version”), this EULA will also govern your use of that POC Version of the Software. For the avoidance of doubt, POC Versions may only be installed to run in End User’s testing environment. End User undertakes not to run POC Versions in its production environment.
                            </li>
                            <li>2.2 Modifications. The Employer Branding Monitor reserves the right, in its sole discretion, to change, modify, add, or remove portions of this EULA on a going forward basis at any time by making such modified EULA available to you on the The Employer Branding Monitor website or through the Software, or both.  The EULA will be identified as of the most recent date of revision and will be effective immediately upon posting, except in the event any such modification materially alters your rights hereunder. In this latter case, The Employer Branding Monitor will notify you directly through a message sent to the email address you have provided to The Employer Branding Monitor, if any, or a pop-up window or other notification when you access or use the Software, in which you will be required to explicitly provide your informed consent with such material modifications. In the absence of such explicit consent, you will be deemed to withdraw your acceptance of this Agreement, in which case you will need to uninstall and discontinue your use of the Software at that time. If you violate this Agreement, The Employer Branding Monitor may terminate your access to and use of the Software.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">3. License grant</h3>
                        <ul>
                            <li>3.1 Subscription License. To the extent reflected in the Order Form, subject to the terms and conditions of this EULA, The Employer Branding Monitor hereby grants to End User a limited, personal, non-transferable, revocable, non-exclusive, without the right to sublicense, worldwide license to use, install and operate the Software on a subscription basis, solely for the purpose of (1) granting the right to access and use the Software to its own internal Concurrent User or Named User; or (2) granting the right to access and use the Software to a third-party Concurrent User or Named User acquiring remote access to the Software as part of End User’s hosting deployment (together the “Subscription License”). The End User shall acquire one Subscription License for each Concurrent or Named User.</li>
                            <li>3.2 Perpetual License. To the extent reflected in the Order Form, subject to the terms and conditions of this EULA, The Employer Branding Monitor hereby grants to End User a limited, paid-up, perpetual (subject only to revocation as provided in this EULA), personal, non-exclusive, non-transferable, without the right to sublicense, worldwide license to use, install and operate the Software, solely for the purpose of (1) granting the right to access and use the Software to its own internal Concurrent User; or (2) granting the right to access and use the Software to a third-party Concurrent User acquiring remote access to the Software as part of End User’s hosting deployment (together the “Perpetual License”). The End User shall acquire one Perpetual License for each Concurrent User, it being understood however that End User’s right to grant remote access to the Software as part of End User’s hosting deployment shall be conditional upon such End User acquiring at least five (5) Perpetual Licenses from The Employer Branding Monitor.</li>
                            <li>3.3 Not-for-Resale License. To the extent reflected in the Order Form, subject to the terms and conditions of this EULA, The Employer Branding Monitor hereby grants to End User a limited, personal, non-transferable, revocable, non-exclusive, without the right to sublicense, worldwide license to use, install and operate the Software solely for the purpose of testing and using it for internal users or for commercial demo purposes only, , and without the right to further distribute, resell or otherwise transfer such licensed rights. For the avoidance of doubt, Not-for-Resale Licenses cannot be used to accommodate end-customers if anything else than for a short term demo.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">4. General licensed rights</h3>
                        <ul>
                            <li>4.1 End User may use, install and operate the Software solely in accordance with terms, conditions, payment requirements, usage limitations and restrictions set forth in (a) this EULA; (b) the Documentation; and (c) the Order Form. In the event of any discrepancy between (i) the provisions set forth in this EULA and (ii) any Order Form, Documentation or written agreement between the End User and The Employer Branding Monitor, such Order Form, Documentation or written agreement shall prevail. In the event of any discrepancy between (i) the provisions set forth in this EULA and (ii) any other communication between the End User and the Reseller, this EULA shall prevail.</li>
                            <li>4.2 End User must acquire a License for each Concurrent User or Named User that wishes to access or use the Software or to which the Software is made available by the End User. The number of Concurrent Users and/or Named Users for which End User has acquired a License is stipulated in the Order Form. End User shall procure that the number of Concurrent Users and/or Named Users shall never exceed the number of Licenses to the Software purchased by such End User. In addition thereto, End User shall procure that the number of Person-based or Device-based Named Users shall never exceed the total number of Named Users reported by the End User in the The Employer Branding Monitor Database. For the avoidance of doubt, End User acknowledges that it must acquire a License for each Device-based Named User that is being accessed or used by or on behalf of the End User, i.e. in case an individual person would use multiple devices to access or use the Software, the End User should acquire a corresponding number of Licenses (one License for each Device-based Named User). Finally, End User shall procure that a Device-based Named User will not be shared by two or more individual users, hence the total amount of users shall never exceed the number of Device-based Named Users for which a License was acquired.</li>
                            <li>4.3 End User hereby acknowledges and agrees that any breach or non-compliance with the present provision shall entitle The Employer Branding Monitor to terminate this EULA in accordance with the provisions set forth in Section 12.2 (ii).</li>
                            <li>4.4 The License does not include the right to sublicense or transfer the End User’s user rights in the Software or the Documentation to any third party by means of sale, lease, loan, rent, license or otherwise, except as explicitly stipulated in this EULA. Except if (1) otherwise explicitly agreed in writing by The Employer Branding Monitor, or (2) to the extent the End User’s use of the Software is governed by applicable EU regulations, for non-commercial purposes, End User is not entitled to resell or distribute the Software or the Documentation.</li>
                            <li>4.5 For the avoidance of doubt, and notwithstanding anything to the contrary herein referencing the “sale” or “purchase” (or similar language) of products or software, the Software is licensed and not sold.</li>
                            <li>4.6 Except for the express License granted to End User pursuant to Section 3.1 or 3.2 of this EULA, all right, title and interest (including all patent, copyright, trademark, trade secret, and other intellectual property and proprietary rights) in and to the Software and Documentation (including all copies thereof) shall remain exclusively in and with The Employer Branding Monitor and/or its licensors, who reserve all rights not expressly granted to End User. Nothing in this EULA shall limit in any way The Employer Branding Monitor’s right to develop, use, license, create derivative works of, or otherwise exploit the Software or the Documentation, or to permit third parties to do so. End User shall reproduce and include all, and shall not remove, alter or obscure, any copyright, trademark and other proprietary notices in and on any copies of the Software and Documentation.</li>
                            <li>4.7	By agreeing to these terms, and by using one and/or multiple licenses on the Employer Branding Monitor, including the Basic (free) license subscription, End User also agrees to, together with the company she/he represents, be named and considered as a customer of The Employer Branding Monitor, and a customer of his parent company, aTalent. The Employer Branding Monitor and aTalent may use any licensed End user and hers/his company logo as part of past, current and future marketing efforts and initiatives.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">5. Usage limitations and restrictions</h3>
                        <ul>
                            <li>5.1 The Software components which are validly licensed by End User and paid for to Reseller (or The Employer Branding Monitor, as the case may be) can be installed and used for such amount (number of Concurrent and/or Named Users, capacity, or other parameter(s)) set forth in the Order Form.  End User agrees to obtain additional Licenses for the Software before it exceeds, or is likely to exceed, any of the limitations applicable to End User’s License.</li>
                            <li>5.2 End User expressly acknowledges and agrees that only End User, and not Reseller nor The Employer Branding Monitor, is responsible for verifying whether the applicable laws and regulations of the country where End User intends to install and use the Software and Documentation, allows the installation and/or use of the Software and Documentation, and for obtaining all necessary permits, licenses and authorisations required to be able to so install and use the Software and Documentation. End User will at all times comply with any and all applicable laws and regulations, including federal, state, local and international laws (“Applicable Law”) which may apply to the Software and Documentation and the installation and use thereof by End User.</li>
                            <li>5.3 End User may not make copies of the Software, except that End User is allowed to make a single copy of the Software solely for backup purposes.</li>
                            <li>5.4 End User will not use the Software or Documentation except as expressly permitted in this EULA.  End User will not, and will not permit any third party to: (a) (attempt to) reverse engineer, decompile, disassemble or otherwise reduce the Software to any human perceivable form, or (b) extract or attempt to extract any source code, algorithms, methods, ideas, techniques, workflows or hierarchies from or embodied in the Software or any portion thereof.  End User may not modify, adapt, install any other software, access the underlying OS, translate, rent, lease, loan or create derivative works based upon, distribute, display or publish (publicly or otherwise), relicense or sublicense the Software, Documentation or any part thereof or use the Software or Documentation for third-party training, commercial time-sharing or service bureau use.</li>
                            <li>5.5 End User agrees to follow the operation procedures published by The Employer Branding Monitor and/or Reseller, as the case may be, including, but not limited to, procedures for routine maintenance of the Software.</li>
                            <li>5.6 End User shall implement, and is solely responsible for implementing, procedures for the protection of data and other information in the event of errors or malfunctions of the Software or hardware on which the Software is used.</li>
                            <li>5.7 End User shall properly train its staff in the use and application of the Software and any hardware on which the Software is used or installed.</li>
                            <li>5.8 Without prejudice to its termination rights set out in section 12.3, The Employer Branding Monitor has the right, at any time during the Term of this EULA, to suspend any license granted hereunder when The Employer Branding Monitor reasonably suspects license abuse by the End User including, but not limited to, any use of the Software by the End User which exceeds the rights granted to such End User under this EULA (e.g. double or more use of the same license for different environments, Internal Use Licenses used in a commercial production environment, etc.). By suspending the license the Software will immediately stop working.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">6. Third-party software</h3>
                        <ul>
                            <li>6.1 End User expressly acknowledges that operation of the Software requires that End User has or obtains, at End User’s sole cost and expense, appropriate hardware and third-party software and/or application licenses, such as (but not limited to) operating systems. Except as expressly stated in Section 6.2, this EULA does not grant any license in or to any other software than the Software, and End User is responsible for procuring all such necessary third-party software or other hardware or equipment.</li>
                            <li>6.2 The Employer Branding Monitor has integrated directly in the Software certain software supplied by third parties. The Employer Branding Monitor provides access to such third-party software as part of the licensed Software. End User acknowledges and agrees that such third-party software is subject to various other terms and conditions imposed by the licensors of such third-party software. As a result thereof, new license keys may possibly need to be activated in respect of Perpetual Licenses from time to time, without additional costs for the End User. A list of third-party software licenses, and the applicable terms thereof, shall be provided with the Software. Such third-party software is provided “AS IS”, with no warranties of any kind. Any third-party software sublicense will terminate when this EULA terminates or when the Software is no longer being used by the End User. End User’s use of such third-party software is subject to, and governed by, the specified third-party license terms, except that this Section 6.2 (Third-Party Software) and Section 10 (Limitation of Liability) of this EULA also govern End User’s use of the third-party software. End User acknowledges that all third-party licensors and suppliers in respect of the Software retain all rights, title and interest in their respective software products. End User agrees to comply with such third-party license terms</li>
                        </ul>

                        <h3 class="mb-3 mt-5">7. License fees</h3>
                        <ul>
                            <li>7.1 General. End User understands and agrees that, if and to the extent the use of the Software is made available as a result of End User’s business relationship with Reseller, End User shall pay Reseller the License Fees and any other amounts owing for the use of the Software (including, but not limited to, related Maintenance and Support Fees), as the case may be, plus any applicable sales, use, excise, or other taxes, as specified by the Reseller’s terms and conditions of sales. When purchasing the licensed rights directly from The Employer Branding Monitor, the End User shall pay the aforementioned fees and amounts directly to The Employer Branding Monitor.
                                All fees payable to Reseller and/or The Employer Branding Monitor, as the case may be, are due and payable pursuant to the terms stipulated in the Order Form. Failure to pay the License Fees and/or other amounts owing for the use of the Software (plus any applicable taxes) may result in termination of the License and related Maintenance and Support Services.
                            </li>
                            <li>7.2 Payments for Subscription Licenses. If licensed under a Subscription License, End User agrees to pay the initial, and, thereafter, the recurring fees for the Subscription License (the “Subscription License Fees”) as described in the original Order Form and based upon the rates and amounts set forth in the original Order Form (subject to adjustment pursuant to Section 7.4).
                                Maintenance and Support Fees are included in the Subscription License Fees. End User also agrees to pay any other fees or charges listed on an Order Form for additional professional services or other services (collectively, the “Other Fees”) separately and upfront, in addition to the Subscription License Fees.
                            </li>
                            <li>7.3 Payments for Perpetual Licenses. If licensed under a Perpetual License, End User agrees to pay upfront the one-off fees for the Perpetual License (the “Perpetual License Fees”) as described in the original Order Form and based upon the rates and amounts set forth in the original Order Form (subject to adjustment pursuant to Section 7.4).
                                Maintenance and Support Fees are not included in the Perpetual License Fees. End User agrees to pay the Maintenance and Support Fees and Other Fees set forth in the Order Form separately and upfront, including, in any event, the Maintenance and Support Fees relating to the Initial Maintenance Period of a Subscription License, which is mandatory to the End User under such License (see Section 8.3).
                                To the extent End User takes delivery of additional licenses (i.e. in the event End User wishes to increase the number of Concurrent or Named Users) the pricing shall be subject to the pricing stipulated in the original Order Form, unless such pricing is amended pursuant to Section 7.4 (in which case such amended pricing shall be applied), and the Maintenance and Support Fees relating to such additional licenses shall be prorated over the balance of the then-current Initial or Subsequent Maintenance Period.
                            </li>
                            <li>7.4 Price Amendments. The Employer Branding Monitor and/or Reseller may amend the Subscription License Fees and/or the Other Fees, provided that such revised or amended Fees shall only become applicable after the termination of the then current license or maintenance term (i.e. the revised or amended License Fees shall apply as from the following Subsequent License Term or Subsequent Maintenance Period only). Any additional Licenses acquired by End User shall be provided at the then applicable Fees (as may be amended from time to time).</li>
                            <li>7.5 Reseller payments. If and to the extent the use of the Software is made available as a result of End User’s business relationship with Reseller, The Employer Branding Monitor acknowledges that End User shall pay all Fees under this EULA directly to Reseller and hereby consents to that arrangement.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">8. Maintenance and support services</h3>
                        <ul>
                            <li>8.1 General. Subject to (i) the payment of the relevant Maintenance and Support Fees by End User, and (ii) the use by such End User of Version N or Version N-1 of the Software as referred to in Section 8.6 hereinafter, Reseller shall provide End User with Maintenance and Support Services, to the extent directly relating to the Software, in accordance with the provisions set forth hereinafter. However, when purchasing the licensed rights directly from The Employer Branding Monitor, the End User shall receive Maintenance and Support Services directly from The Employer Branding Monitor.</li>
                            <li>8.2 Subscription License. Each Subscription License shall include the right to receive Maintenance and Support Services. Maintenance and Support Services may not be separated from the Subscription License and may not be terminated without also terminating the Subscription License.</li>
                            <li>8.3 Perpetual License. With respect to the Perpetual Licenses, End User shall subscribe separately to the Maintenance and Support Services on an annual basis and for such number of Concurrent Users and/or Named Users as set out in the Order Form. End User hereby purchases Maintenance and Support Services at the price set forth in the Order Form for a term as indicated in the Order Form, including at least the first year as from the Delivery Date (the “Initial Maintenance Period”), during which term the Maintenance and Support Services are mandatory under Perpetual Licenses. The Initial Maintenance Period may be extended to three (3) years if so provided in the Order Form. Upon expiration of the Initial Maintenance Period, End User’s subscription to the Maintenance and Support Services relating to Perpetual Licenses shall be automatically renewed at Reseller’s then current rates for subsequent terms of the same duration (i.e. one year each or three years each) (the “Subsequent Maintenance Periods”), unless explicitly terminated by either the Reseller or the End User at the end of the Initial Maintenance Period or at the end of any Subsequent Maintenance Period upon giving a three (3) months prior written notice by registered mail to the terminated party (either The Employer Branding Monitor or End User), starting the first day of the month following the date of delivery of such termination notice. The aforementioned termination rights are without prejudice to the specific termination rights set forth under subsequent Section 8.4.                         In case End User purchases Maintenance and Support Services for less (Concurrent or Named) Users than the number of Concurrent Users and/or Named Users for which End User has acquired a Perpetual License, then only the number of Concurrent Users and/or Named Users covered under the latest Maintenance & Support Services purchase will be eligible to access the The Employer Branding Monitor platform, and the scope of the Perpetual License will be reduced accordingly until additional Maintenance and Support Services are acquired in respect of the balance of Concurrent Users and/or Named Users. For the avoidance of doubt, the surplus in Concurrent Users and/or Named Users that were initially purchased under a Perpetual License will only be temporarily suspended until the relevant Maintenance and Support Services are acquired in respect of such Concurrent Users and/or Named Users).</li>
                            <li>8.4 Price Amendments. At least fifteen (15) days prior to the expiration of any Maintenance Period, Reseller or The Employer Branding Monitor (as the case may be) may provide notice to End User of the amended Maintenance and Support Fees for the upcoming Maintenance Period. Thereafter, with respect to all Concurrent Users under license, End User may elect to (i) renew Maintenance and Support Services at the amended fee rates, or (ii) elect not to renew Maintenance and Support Services. If no written notice is provided to Reseller or The Employer Branding Monitor, as the case may be, prior to the expiration of any Maintenance Period, there shall be an automatic renewal of Maintenance and Support Services at Reseller’s or The Employer Branding Monitor’s revised Maintenance and Support Fees.</li>
                            <li>8.5 Software Maintenance. Subject to the payment of the relevant Maintenance and Support Fees, The Employer Branding Monitor shall provide End User, from time to time, with Updates (including periodic distribution of bug fixes, maintenance releases and minor enhancements) as scheduled by The Employer Branding Monitor in its sole discretion. End User may refuse to accept an Update.
                                The Maintenance and Support Services shall be exclusive of any Upgrades to the Software. In order for End User to receive and use such Upgrade, End User must (i) pay the applicable License Fees for that Upgrade; (ii) to the extent not included in such applicable License Fees, pay the applicable Maintenance and Support Fees for the then current Maintenance Period. Unless explicitly stated otherwise, the terms of this EULA shall apply and the Upgrade shall be deemed Licensed Software upon payment by End User of the applicable License Fees.</li>
                            <li>8.6 Support Services. Upon each new release (regardless whether such release constitutes an Upgrade or an Update), The Employer Branding Monitor shall maintain only the Version of the Product that has been thus revised (hereinafter: “Version N”) and the previous Version (hereinafter “Version N-1”). End User shall be eligible for such Maintenance and Support Services only if and to the extent (i) End User has duly paid the applicable Maintenance and Support Fees; and (ii) End User is using Version N and/or Version N-1 of the Software. In case End User’s right to Support and Maintenance Services is terminated as a result of a new release of the Software (either an Update or an Upgrade, End User shall not be entitled to any refunds of Maintenance and Support Fees.</li>
                            <li>8.7 Response to Inquiries. Subject to End User’s payment of the applicable Maintenance and Support Fees, (i) End User’s installation support inquiries will be accepted by Reseller (or in case the End User acquired the Software directly from The Employer Branding Monitor, by The Employer Branding Monitor) during normal business hours; and (ii) End User’s technical support inquiries are accepted at any time and will be answered during normal business hours. Reseller (or The Employer Branding Monitor, as the case may be) will attempt to respond to inquiries within the same business day.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">9. Warranties</h3>
                        <ul>
                            <li>9.1 Software Warranty. Except for the POC Versions of the Software, for which no warranty is provided (i.e. POC Versions are provided “AS IS”), The Employer Branding Monitor warrants that the Software will perform substantially in accordance with the applicable part of the Documentation for a period of sixty (60) days following the date on which the Software is delivered to End User or otherwise made available to End User for download (the “Warranty Period“) when maintained and operated in accordance with the License and the Documentation (“Software Warranty”).
                                THE SOFTWARE WARRANTY WILL NOT APPLY IF ANY FAILURE, ERROR, DEFECT OR MALFUNCTION RESULTS FROM ANY MISUSE OF THE SOFTWARE OR IS OTHERWISE NOT ATTRIBUTABLE TO THE Employer Branding Monitor. THE Employer Branding Monitor MAKES NO REPRESENTATION OR WARRANTY (I) THAT THE SOFTWARE WILL MEET END USER’S REQUIREMENTS, (II) THAT ALL ERRORS, DEFECTS, OR MALFUNCTIONS HAVE BEEN OR CAN BE ELIMINATED FROM THE SOFTWARE, (III) THAT THE SOFTWARE IS FREE OF ERRORS, DEFECTS, VIRUSES OR MALFUNCTIONS, OR THAT THE SOFTWARE WILL OPERATE WITHOUT INTERRUPTION, OR (IV) THAT THE SOFTWARE WILL OPERATE WITH OTHER HARDWARE, SOFTWARE, SYSTEMS OR DATA, AND RESELLER SHALL IN NO EVENT BE RESPONSIBLE FOR LOSSES OF ANY KIND RESULTING FROM THE USE OF THE SOFTWARE, INCLUDING, WITHOUT LIMITATION, ANY LIABILITY FOR BUSINESS EXPENSE, MACHINE DOWNTIME, LOSS OF OR CORRUPTION TO DATA, OR DAMAGES CAUSED TO END USER OR THIRD PARTIES BY ANY DEFICIENCY, DEFECT, ERROR OR MALFUNCTION. THE SOFTWARE WARRANTY APPLIES ONLY TO THE ORIGINAL END USER AND IS NOT TRANSFERABLE TO ANY THIRD PARTY OR ASSIGNEE OF END USER.
                                If End User fails to pay when due any payment required from End User to Reseller or The Employer Branding Monitor under this EULA or otherwise, the Software Warranty and the related remedies of End User will automatically become null and void and of no further force or effect.
                                End User must notify The Employer Branding Monitor by email or through other contact mechanisms provided by The Employer Branding Monitor of any breach of the Software Warranty within the Warranty Period.</li>
                            <li>9.2 Remedies. Subject to the limitations set forth in the subsequent Section 10 entitled “Limitation of Liability”, End User’s exclusive remedy, and The Employer Branding Monitor’s entire liability, arising from any breach of the Software Warranty shall be, at The Employer Branding Monitor’s option and at no cost to End User, for The Employer Branding Monitor to (i) make commercially reasonable efforts to correct or provide a reasonable Workaround for the failure, error, defect or malfunction that caused the breach of the Software Warranty, or (ii) replace the (defective part of the) Software. If any breach of Software Warranty claim by End User falls within any of the exceptions listed above in the first paragraph of the present Section “Warranties”, End User shall upon The Employer Branding Monitor’s request pay The Employer Branding Monitor for such assistance and services provided by The Employer Branding Monitor in respect thereof on a time and material basis at The Employer Branding Monitor’s then current professional services rates and related expenses.</li>
                            <li>9.3 Disclaimer. THE SOFTWARE WARRANTY IS IN LIEU OF ALL OTHER REPRESENTATIONS, WARRANTIES AND COVENANTS, EXPRESS OR IMPLIED, WITH RESPECT TO THE SOFTWARE AND DOCUMENTATION.  TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, THE Employer Branding Monitor EXPRESSLY DISCLAIMS ALL OTHER WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, WITH RESPECT TO THE SOFTWARE AND DOCUMENTATION, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, PURPOSE, SATISFACTORY QUALITY, ACCURACY, TITLE AND NON-INFRINGEMENT AND ANY WARRANTIES THAT MAY ARISE OUT OF COURSE OF PERFORMANCE, COURSE OF DEALING OR USAGE OF TRADE.  USE OF THE SOFTWARE BY END USER IS AT END USER’S SOLE RISK.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">10. Limitation of liability</h3>
                        <ul>
                            <li>10.1 Exclusion of indirect damages. In no event shall The Employer Branding Monitor be liable to End User or any third party under any theory of liability for lost profits and/or any other indirect, incidental, consequential, special or punitive damages, however caused, including, without limitation, (i) loss of revenue, business or use; (ii) loss of anticipated savings; (iii) loss of actual or anticipated business and/or goods; (iv) loss of goodwill; (v) loss and/or corruption of data and/or other information, (vi) loss as a result of third party claims; and/or (vii) the cost of procuring replacement goods and/or services. For the avoidance of doubt, the types of loss and/or damage specified in (i) through (vii) shall not constitute direct losses for the purposes of this EULA.  The foregoing limitation will apply even if The Employer Branding Monitor has been advised of the possibility of such damages or if such damages are foreseeable.</li>
                            <li>10.2 Cap on other damages. Notwithstanding any other provision of this EULA, and to the fullest extent allowed under Applicable Law, The Employer Branding Monitor’s aggregate liability of all kinds towards End User for any damages arising from or related to the Software, the Documentation, the Professional Services or this EULA, other than as set out under 10.1 above, whether for breach, infringement, in tort, indemnification or otherwise, shall be limited to an aggregate amount equal to either (i) the license fees in respect of the Software only (excl. any taxes) actually received by Reseller or The Employer Branding Monitor for End User’s use of the Software during the six (6) month period preceding End User’s initial notice to The Employer Branding Monitor of any claim or potential claim hereunder; or (ii) 50,000 EUR, whichever amount is lower. The existence of one or more claims under this EULA shall not enlarge the limit.</li>
                            <li>10.3 No limitations for The Employer Branding Monitor’s own intent. The aforementioned limitations and exclusions will not apply in the event the liability results from The Employer Branding Monitor’s proven willful intent or gross negligence, or that of its subordinates or assistants.</li>
                            <li>10.4 Employees and agents. The limitations and exclusions of liability, as well as indemnity stipulated for The Employer Branding Monitor itself in the present EULA are also stipulated for and on behalf of The Employer Branding Monitor’s directors, employees, agents and other intermediaries and/or any other person employed by it or delivering services to it within the framework of the EULA.</li>
                            <li>10.5 Limitation in time. End User may not bring a claim under this EULA more than twelve (12) months after the cause of action arises.</li>
                            <li>10.6 Specific exclusion for Professional Services. Without prejudice to the provisions of article 10.1 and 10.2 above, any recommendations made by The Employer Branding Monitor to End User as part of its provision of Professional Services (either in the Documentation, in writing, by e-mail or verbally) are and shall remain the End User’s sole and exclusive responsibility, regardless whether the relevant recommended actions are executed by The Employer Branding Monitor or End User (or any third party on behalf of End User). In view thereof, End User explicitly accepts to assess and to determine in its own discretion any risks relating to any proposed amendments or changes to End User’s surrounding infrastructure and/or applications (such as AD, Appserver, Storage, Firewall, etc.).</li>
                            <li>10.7 General exclusion for POC Versions. Notwithstanding any other provisions set out herein, when provided as a POC Version, the Software is provided “AS IS”, excluding any liability on behalf of The Employer Branding Monitor and/or its Reseller, on any basis, in contract, tort or otherwise, of any kind and nature whatsoever, arising in respect of this EULA, howsoever caused, including for damages of any kind and nature caused by The Employer Branding Monitor and/or Resellers’ negligence.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">11. IP infringements</h3>
                        <ul>
                            <li>11.1 In the event of a claim that the Software and/or Documentation, or End User’s permitted use thereof under this EULA, infringes a third party’s intellectual property, proprietary or other right, or The Employer Branding Monitor’s belief that such claim is likely to arise, The Employer Branding Monitor shall have the right, at its sole option and expense: to (a) procure for End User the right to continue using the affected Software and/or Documentation; (b) replace or modify the affected (part of the) Software and/or Documentation so that it does not infringe; or (c) terminate this EULA.  If The Employer Branding Monitor so terminates this EULA, as End User’s sole remedy and The Employer Branding Monitor’s entire liability, The Employer Branding Monitor will pay to End User, upon End User’s certified deletion of the affected Software, an amount equal to the License Fees paid hereunder for the License in respect of the affected Software, prorated from the Delivery Date, based on a straight line depreciation, through the date the License is terminated over the original term of the License.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">12. Term and termination</h3>
                        <ul>
                            <li>12.1 Term. The term of this EULA shall commence on the Delivery Date, and will remain effective during:
                                <br>(1) the Initial License Term and Subsequent License Term (in case of a Subscription License), it being understood that a Subscription License shall be automatically renewed at the end of the Initial License Term or each Subsequent License Term, each time for a Subsequent License Term, unless explicitly terminated in accordance with the provisions of this Section 12; or
                                <br>(2) for an indefinite term (in case of a Perpetual License), except if terminated earlier in accordance with the provisions of this Section 12.
                            </li>
                            <li>12.2 Termination upon notice. A Subscription License can be terminated at the end of the relevant Initial License Term or at any time during a Subsequent License Term upon giving a two (2) months prior written notice by registered mail to The Employer Branding Monitor (or, if terminated by The Employer Branding Monitor, to the relevant End User), starting on the first day of the month following the date of delivery of such termination notice.</li>
                            <li>12.3 Termination for Cause. Without prejudice to either party’s other rights accorded to it by this EULA (especially the termination rights under Section 2.2) or by law, either party can terminate this EULA with immediate effect by written notice to the other party, if any of the following events occur: (i) the other party breaches this EULA and fails to cure such breach within thirty (30) days of the receipt of written notice of such breach from the non-breaching party; (ii) the other party breaches this EULA, and such breach is not curable (a breach of the License terms by End User shall be deemed a breach which is not curable); (iii) the other party makes a general assignment for the benefit of creditors, files a voluntary petition of bankruptcy, becomes subject to any proceedings under any bankruptcy or insolvency law (whether domestic or foreign), has wound up or liquidated, voluntarily or otherwise; (iv) the other party becomes insolvent or ceases or threatens to cease to carry on its business in the normal course; (v) the other party suffers or permits the appointment of a receiver for its business or assets; or (vi) any other event analogous to those listed under (iii) through (v) occurs in the jurisdiction applicable to the party affected. The affected party shall promptly notify the other party in the event of the occurrence of any of the foregoing instances as per (iii) through (v). Termination by either Party pursuant to this Section 12.3 shall not entitle the other Party to any refund of any prepaid License Fees or Other Fees.</li>
                            <li>12.4 Effect of Termination. If the term of this EULA expires or is terminated for any reason whatsoever, the License shall automatically terminate as set forth above and End User shall: (i) immediately cease using the Software and the Documentation; (ii) have an End User senior officer certify to Reseller within thirty (30) days after the effective date of termination that End User has permanently deleted, destroyed, or, at The Employer Branding Monitor’s option, has returned to The Employer Branding Monitor the Documentation and all copies thereof.  Neither party shall be liable to the other for damages of any kind solely as a result of terminating this EULA in accordance with this section 12.  Either party’s termination of this Agreement shall be without prejudice to any other right or remedy that it may have at law or in equity, and shall not relieve either party of breaches occurring prior to the effective date of such termination.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">13. Verification</h3>
                        <ul>
                            <li>13.1 During the term of this EULA and for a period of three (3) years from the expiration or termination thereof, End User shall maintain accurate records of its use of the Software sufficient to demonstrate its compliance with the terms of this EULA and all Order Forms.</li>
                            <li>13.2 Upon ten (10) days’ notice to End User, The Employer Branding Monitor and/or Reseller shall have the right to (or to have a third party) inspect and audit such End User’s records and its systems to confirm End User’s compliance with the provisions of this EULA. Such audit rights shall be subject to The Employer Branding Monitor’s (or the relevant Reseller or third party) compliance with End User work site rules, and no interference with End User’s business. End User agrees to fully cooperate with any such inspection and audit and shall provide all access to such records and its systems as reasonable required for The Employer Branding Monitor and/or Reseller to confirm End User’s compliance with the terms hereof.</li>
                            <li>13.3 In the event that the audit reveals unauthorized use of the Software, or use beyond the scope of the usage limitations and restrictions applicable to the Software, then, without prejudice to The Employer Branding Monitor’s other rights (including termination of the License), End User shall promptly pay the relevant License Fees (i.e. either the Subscription License Fees in case End User uses Subscription Licenses, or Perpetual License Fees in case End User uses Perpetual Licenses) and, in case of a Perpetual License, the Maintenance and Support Fees relating to the Initial Maintenance Period, in order to cover all use of the Software disclosed by the audit starting from the date the unlicensed use was presumed to have begun, plus a reinstatement fee of fifty percent (50%) of the applicable License Fees payable for such unlicensed use.  End User agrees that all unlicensed use of the Software shall be presumed to have started on the first day on which the Software was made available to End User (through key download, delivery or otherwise), unless End User proves otherwise to the satisfaction of The Employer Branding Monitor.
                                <br>If the audit determines that End User underpaid the License Fees by more than five percent (5%), End User shall pay The Employer Branding Monitor’s reasonable costs and expenses for the audit (including transportation, travel, and if applicable the cost of the third party auditor).
                            </li>
                            <li>13.4 This Section 13 shall survive the termination of this EULA for any reason, and shall stay effective until three (3) years after the termination of this EULA.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">14. Confidentiality obligations</h3>
                        <ul>
                            <li>14.1 End User agrees to keep the Confidential Information of The Employer Branding Monitor confidential and not to disclose it to third parties, unless expressly otherwise agreed by a duly authorized representative of The Employer Branding Monitor. End User shall be entitled to disclose The Employer Branding Monitor’s Confidential Information only to those of its personnel, consultants and agents that have a reasonable need to know such Confidential Information for the purposes of this EULA, and provided the End User instructs its personnel, consultants and agents to keep such information confidential by using the same care and discretion that it uses for its own Confidential Information and in no event, less than a reasonable degree of care.</li>
                            <li>14.2 The obligations set forth in this Section 14 shall not apply to any information which: (i) is published or otherwise becomes available to the general public through no fault of End User; (ii) has been validly obtained by End User from a third party not being bound by any confidentiality or similar secrecy obligation; (iii) was in End User’s possession without proprietary restrictions prior to the date of disclosure by The Employer Branding Monitor and/or Reseller to End User; (iv) was developed by End User without reference to the Confidential Information; or (v) is required to be disclosed pursuant to Applicable Law, to the extent of such requirement only and provided that End User shall, if feasible, give to Reseller and/or The Employer Branding Monitor prior notice of such proposed disclosure and a reasonable opportunity to contest such disclosure.</li>
                            <li>14.3 This Section 14 shall survive the termination of this EULA for any reason, and shall stay effective until three (3) years after the termination of this EULA.</li>
                        </ul>

                        <h3 class="mb-3 mt-5">15. Privacy and data collection</h3>
                        <ul>
                            <li>15.1 The Employer Branding Monitor’s privacy policy (the “Privacy Policy”) sets forth how The Employer Branding Monitor collects, uses, and protects any personal data which End User may provide to it. A copy of the Privacy Policy is available at https://www.atalent.com/security-privacy-statement, which is incorporated herein by reference and forms an essential part of this EULA.</li>
                        </ul>


                        <h3 class="mb-3 mt-5">16. Miscellaneous terms</h3>
                        <ul>
                            <li>16.1 Export and Government Restrictions.  End User may not export or re-export the Software in violation of any applicable laws or regulations including but not limited to those of the People's Republic of China, the United States of America and the European Union. In addition, if the Software is identified as export controlled items under the export laws of the United States of America or the European Union, End User represents and warrants that he/she is not a citizen, or otherwise located within, an embargoed nation and that he/she is not otherwise prohibited under applicable export laws from receiving the Software. Moreover if End User’s acquisition of the Software is subject to the laws of the United States of America, End User represents and warrants that he/she will comply with any specific restrictions and regulations that might be applicable to all contracts or agreements (including but not limited to the reproduction of the “restricted rights” proprietary notices and/or legends) concluded with the United States government or its agents and representatives. All rights to use the Software are granted on the condition that those rights are forfeited if End User fail to comply with the terms of this EULA.</li>
                            <li>16.2 Assignment. Either party may assign and/or transfer this EULA in whole or in part to its successors or to any third party or entity acquiring all or substantially all of such party’s assets, subject to prior written notification thereof to the other party.</li>
                            <li>16.3 Severability. If any part of this EULA is found by a court of competent jurisdiction or other competent authority to be invalid, unlawful or unenforceable then such part will be severed from the remainder of this EULA, which will continue to be valid and enforceable to the fullest extent permitted by Applicable Law. The invalid or unenforceable part or provision shall be replaced with a provision which accomplishes, to the extent possible, the original business purpose of such part or provision in a valid and enforceable manner.</li>
                            <li>16.4 Representations. Each party represents and warrants to the other that it has full authority to enter into this EULA, that the execution and/or performance of this EULA does not and will not violate or interfere with any other agreement by which such warranting party is bound; and that the warranting party will not enter into any agreement whose execution/performance would violate or interfere with this EULA.</li>
                            <li>16.5 Survival. The rights and obligations under this EULA which by their nature should survive, including but not limited to all rights and obligations in Sections 10, 4, 13, 14 and 16 of this EULA will remain in effect after any termination or expiration hereof.</li>
                            <li>16.6 References. End User agrees that The Employer Branding Monitor may use End User’s name and logo in press releases, product brochures, financial reports and other promotional materials in any media indicating that End User makes use of the The Employer Branding Monitor Software.</li>
                            <li>16.7 Notices. Except as otherwise provided herein, all notices, consents, requests, instructions, approvals and other communications made, required, or permitted under this EULA will be given at the addresses set forth in the Order Form, by (i) personal service, deemed effective on the reported delivery date; (ii) recognized international or overnight courier, deemed effective on reported delivery date; or (iii) email transmission against receipt confirmation, deemed effective on delivery date confirmation.</li>
                            <li>16.8 Entire Agreement.  This EULA, together with the Order Form constitutes the entire agreement between the The Employer Branding Monitor and the End User, and supersede all prior or contemporaneous agreements or representations, written or oral, concerning the subject matter of this Agreement.</li>
                            <li>16.9 Governing Law; Venue. This EULA is governed by and will be interpreted in accordance with the laws of the People's Republic of China, without reference to its conflicts of law provisions.  Any dispute regarding this Agreement shall be subject to the exclusive jurisdiction of the courts of Shanghai, People's Republic of China, and the parties hereby irrevocably agree to submit to the personal and exclusive jurisdiction and venue of such courts.</li>
                            <li>16.10 English Language.  This EULA is drafted in the English language only, which language shall be controlling in all respects, and all versions hereof in any other language shall be for accommodation only and shall not be binding upon the parties. All communications and notices to be made or given pursuant to this Agreement shall be in the English language.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
